### PR TITLE
Fix #11 by separating the responsibility to store and run hooks

### LINKED ISSUE #11: Unused hooks report invalid arguments
## summary

**When** I make a simple hook server with the goodman library...
**I expect** hooks I don't implement to be ignored.
**Instead** I get warnings
**Even though** the hooks I did implement work properly.
### my hook server

``` go
package main

import (
    "fmt"

    "github.com/snikch/goodman/hooks"
    trans "github.com/snikch/goodman/transaction"
)

func main() {
    h := hooks.NewHooks()
    server := hooks.NewServer(h)

    h.BeforeAll(func(t []*trans.Transaction) {
        fmt.Println("THIS IS A DREDD TEST HOOK WRITTEN IN GOLANG BeforeAll starting.")
    })

    server.Serve()
    defer server.Listener.Close()
}
```
### unexpected error messages

```
info: Hook handler stdout: Completed

info: Hook handler stderr: 2016/07/14 11:57:40 Starting hooks server in go routine

info: Hook handler stderr: 2016/07/14 11:57:40 method After reply type not a pointer: hooks.Callback
2016/07/14 11:57:40 method AfterAll has wrong number of ins: 2
2016/07/14 11:57:40 method AfterEach has wrong number of ins: 2
2016/07/14 11:57:40 method Before reply type not a pointer: hooks.Callback
2016/07/14 11:57:40 method BeforeAll has wrong number of ins: 2
2016/07/14 11:57:40 method BeforeEach has wrong number of ins: 2
2016/07/14 11:57:40 method BeforeEachValidation has wrong number of ins: 2
2016/07/14 11:57:40 method BeforeValidation reply type not a pointer: hooks.Callback
```
### Successful portion

```
info: Hook handler stdout: Starting

info: Hook handler stdout: Accepting connection

info: Connected to the hook handler, waiting 0.1s to start testing.
info: Hook handler stdout: THIS IS A DREDD TEST HOOK WRITTEN IN GOLANG BeforeAll starting.

```

### PR DESCRIPTION
**Pull request by IngmarStein**
This PR fixes the warnings printed for each method in Hooks that doesn't have a matching signature for RPC.

### CODE REVIEW

**Comment by ddelnano** [comment]
@IngmarStein thanks for opening this!  I have been meaning to get these fixed but haven't gotten around to it.  Unfortunately the e2e tests seem to be failing.  Since they haven't been run in a while I opened #28 to just test master to make sure any upstream dredd changes did not change anything (since the dredd version is not pinned in the build).  Since that passed these changes have caused a breakage.  I'll try to look at this sometime today to dig into why its failing.

**Comment by IngmarStein** [comment]
I think one of the issues is that the example app vendors a specific goodman version which of course doesn't include the commits above and therefore doesn't compile. The vendor.json file could be updated after merging.
Not sure about the TimeoutErrors though…

**Comment by IngmarStein** [comment]
The cucumber tests now pass and the only remaining error is due to the old vendored goodman code in the example app. I hope you don't mind adding Go 1.8 to the test matrix.

File: cmd/goodman/main.go [hunk 1]
```diff
@@ -51,7 +51,7 @@ func main() {
 				}
 			}()
 			for retries := 5; retries > 0; retries-- {
-				runner, err := goodman.NewRunner("Hooks", hookServerInitalPort)
+				runner, err := goodman.NewRunner("HooksRunner", hookServerInitalPort)
```
Comment (ddelnano) [inline cmd/goodman/main.go]: 😢 for magic strings.  I wonder if its possible to look this up using reflection or some other mechanism?

**Comment by ddelnano** [comment]
@IngmarStein +1 for the addition of Go 1.8.

File: cmd/goodman/main.go (hunk 1 above)
Comment (IngmarStein) [reply cmd/goodman/main.go]: That would look like this:
```
rpcService := reflect.TypeOf((*hooks.HooksRunner)(nil)).Elem().Name()
for retries := 5; retries > 0; retries-- {
	runner, err := goodman.NewRunner(rpcService, hookServerInitalPort)
```
and needs an import of `github.com/snikch/goodman/hooks`
Do you prefer that?

Comment (ddelnano) [reply cmd/goodman/main.go]: I'm guessing this was the change that fixed the timeouts correct?

I was hoping to introduce a change that threw a more obvious error instead of experiencing timeouts.  Now that I think about it I don't think that would have changed anything.  I'm fine with things either way.

Comment (IngmarStein) [reply cmd/goodman/main.go]: Yep, that was the cause for the timeouts.

I've pushed the change to retrieve the struct name via reflection.

**Comment by ddelnano** [comment]
@IngmarStein can we remove the vendoring of the goodman packages from the example's vendor.json?  I think that will fix the example run in the CI build.  I want to keep that apart of the CI build to make sure its always working but didn't realize the drawbacks of vendoring it like I did.

I did a proof of concept in #29 to see if it would still pass and I'm hoping if you make the same change it will work.

Once the example works I think this is good to merge.

**Comment by ddelnano** [comment]
@IngmarStein going to merge and tag a new release!  Thanks for fixing this.
